spring:
   profiles:
     active: development
server:
    port: 8000
---
spring:
    profiles: development
    main:
       show_banner: false
spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_radio?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: dragon3s12
server:
    port: 8000
---
spring:
    profiles: production
    main:
       show_banner: true
spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:61254/api_radio?useUnicode=yes&characterEncoding=UTF-8
    initialize: false
    username: root
    password: Trex12sk
server:
    port: 8000